#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

./manage.py migrate
# ./manage.py collectstatic --skip-checks --noinput
uvicorn app.asgi:app --host 0.0.0.0 --port 8000 --reload --reload-include '*.html'
